### PR TITLE
Updated sloc package version.

### PR DESCRIPTION
**Pull request by andrewmcwatters**

### CODE REVIEW

**Comment by sgade** [comment]
Seems to work. Will merge. Thank you!

**Comment by andrewmcwatters** [comment]
Thank you! Could you release tag `v1.0.1` as well for Atom? This should fix apm installing the old `sloc` dependency and not supporting the newer languages added since `sloc v0.0.8`.

**Comment by sgade** [comment]
I have. Should be published right now. 🚀
Let me know if anything is still missing.

**Comment by sgade** [comment]
I have looked into the code once more and finally decided to get rid of the hard-coded `supportedLanguages` array. I understand your pull request was primarily because you wanted all the languages that the sloc package supports. This should now be possible. Version 1.1.0 is out now.

**Comment by andrewmcwatters** [comment]
Wow, thanks!! Great package, by the way!

**Comment by sgade** [comment]
Thanks.

**Pull request merged**
