### PR TITLE
refreshing sloc when switching between buffers

### LINKED ISSUE #6: sloc does not auto-update when switching between opened files
`sloc` does not auto-update when switching between opened files. It will only show the information regarding the newly switched file after the first alteration to that file.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #6

`sloc` now refreshes line count when switching between different buffers.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@sgade My apologies, I did not mean to replace the first event. It seems to be working as it should right now.

**Comment by sgade** [comment]
Thanks again!

**Comment by gilbertohasnofb** [comment]
My pleasure!

**Comment by gilbertohasnofb** [comment]
@sgade if you are not planning to make any new commits to this project in the near future, would you consider making a new release when you have a chance as to include these modifications? Thanks!

**Comment by sgade** [comment]
@gilbertohasnofb Version 1.1.1 should be available via apm.

**Pull request merged**
